# Generated by Django 3.2.25 on 2024-12-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='body',
        ),
    ]
