# Generated by Django 3.2.25 on 2024-12-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contactformsubmission_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasolutioncategory',
            name='name',
            field=models.CharField(choices=[('DM', 'Data Management'), ('DE', 'Data Integration & Automation'), ('DA', 'Business Insights & Analytics'), ('DS', 'Machine Learning & AI'), ('SP', 'Data Security & Privacy'), ('CD', 'Cloud Data Solutions'), ('OT', 'Other Services')], default='OT', max_length=2),
        ),
    ]
