# Generated by Django 3.2.25 on 2025-01-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_datasolutioncategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasolutioncategory',
            old_name='description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='datasolutioncategory',
            name='bg_img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategory',
            name='bi_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategory',
            name='code',
            field=models.CharField(choices=[('DM', 'Data Strategy & Management'), ('DE', 'Data Integration & Automation'), ('DA', 'Business Insights & Analytics'), ('DS', 'Machine Learning & AI'), ('SP', 'Data Security & Privacy'), ('CD', 'Cloud Data Solutions'), ('OT', 'Other Services')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='datasolutioncategory',
            name='desc_short',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategory',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategory',
            name='name_alternate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategory',
            name='name_full',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasolutioncategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
