# Generated by Django 3.2.25 on 2025-01-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20250102_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasolutioncategory',
            name='desc_oneliner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
