# Generated by Django 3.2.25 on 2025-01-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_datasolutioncategory_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSolutionCategorySection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=200)),
                ('subheader', models.CharField(blank=True, max_length=300, null=True)),
                ('list_header', models.CharField(blank=True, max_length=200, null=True)),
                ('list_items', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='portfolio.datasolutioncategory')),
            ],
        ),
    ]
