# Generated by Django 3.2.25 on 2025-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_datasolutioncategorysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasolutioncategorysection',
            name='list_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
