# Generated by Django 3.2.25 on 2025-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20250103_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasolutioncategorysection',
            name='list_items',
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_desc1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_desc2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_desc3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_desc4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_header1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_header2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_header3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_header4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_icon1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_icon2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_icon3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='list_item_icon4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
