# Generated by Django 3.2.25 on 2025-01-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20250103_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasolutioncategorysection',
            name='extra',
        ),
    ]
