# Generated by Django 3.2.25 on 2025-01-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_datasolutioncategorysection_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasolutioncategorysection',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
