# Generated by Django 3.2.25 on 2025-01-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_datasolutioncategorysection_sequence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSolutionCategorySection',
        ),
    ]
