# Generated by Django 3.2.25 on 2025-01-03 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_delete_datasolutioncategorysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSectionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.servicesectiontype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sections', to='portfolio.datasolutioncategory')),
            ],
        ),
    ]
