# Generated by Django 3.2.25 on 2025-01-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_servicesection_servicesectiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
