# Generated by Django 3.2.25 on 2025-01-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_servicesection_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='content_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
