# Generated by Django 3.2.25 on 2025-01-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_servicesection_content_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasolutioncategory',
            name='code',
            field=models.CharField(choices=[('DM', 'Data Strategy & Management'), ('DE', 'Data Integration & Automation'), ('DA', 'Business Insights & Analytics'), ('DS', 'Machine Learning & AI'), ('SP', 'Data Security & Privacy'), ('CD', 'Cloud Data Solutions'), ('OT', 'Other Services'), ('WD', 'Web Design')], default='OT', max_length=2),
        ),
    ]
